//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Probabilidad
    {
        public int idProbabilidad { get; set; }
        public string categoria { get; set; }
        public string descripcion { get; set; }
        public int rangoInicio { get; set; }
        public int rangoFin { get; set; }
        public int valor { get; set; }
    }
}
