//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riesgo
    {
        public int idRiesgo { get; set; }
        public Nullable<int> puntuajePI { get; set; }
        public string descripcion { get; set; }
        public string categoria { get; set; }
        public string disparador { get; set; }
        public string accionarDisparador { get; set; }
        public string tipoRespuesta { get; set; }
        public string descripcionRespuesta { get; set; }
        public string resultadoRespuesta { get; set; }
        public string resultadoEsperado { get; set; }
        public string encargadoMonitoreo { get; set; }
        public string encargadoRespuesta { get; set; }
        public string nivel { get; set; }
        public string color { get; set; }
        public int idImpacto { get; set; }
        public int idProbabilidad { get; set; }
    
        public virtual Impacto Impacto { get; set; }
        public virtual Probabilidad Probabilidad { get; set; }
    }
}
